import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import ConvexClerkProvider from '../components/providers/ConvexClerkProvider'
import Navbar from '../components/Navbar'
import { ThemeProvider } from '../components/providers/ThemeProvider'

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jetbrainsMono.variable} antialiased font-mono`}>
        <ConvexClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              <Navbar />
              <main className='px-4 sm:px-6 lg:px-8'>
                {children}
              </main>
            </div>
          </ThemeProvider>
        </ConvexClerkProvider>
      </body>
    </html>
  )
}